### PR TITLE
Implement Continuous Deployment to Spaces

### LINKED ISSUE #23: Implement Continuous Deployment to Spaces
Implement automatic Continuous Deployment (CD) from GitHub to Spaces.

### PR DESCRIPTION
**Pull request by albertvillanova**
Add GitHub Action to deploy to Spaces.

Fix #23.

### CODE REVIEW

**Comment by albertvillanova** [comment]
Before merging this PR, I need admin rights to set the repository secret `HF_TOKEN` with my user API token, so that the repo can be pushed to the Hugging Face Hub Spaces.

Is there a better way?

CC: @julien-c @thomwolf

**Comment by julien-c** [comment]
I think that's the most correct way at the moment, but tagging @SBrandeis and @Pierrci who are currently revamping the token system, for visibility.

**Comment by SBrandeis** [comment]
IMO this is the way to go with the current state of everything

If you're not comfortable using your token @albertvillanova, an alternative would be to create a machine user specifically for this and use its credentials.

**Comment by Narsil** [comment]
Unrelated @SBrandeis but I would Love to have machine specific tokens for things like this on the API (both CI/CD and integration tests)

**Comment by julien-c** [comment]
@Narsil There's a current PR by @SBrandeis that should fit your use case perfectly if you two want to discuss it a little bit

**Comment by albertvillanova** [comment]
@julien-c Is it this one?
- huggingface/moon-landing#1434

**Comment by albertvillanova** [comment]
In relation with this PR, I'm OK with using my personal token for the moment (as it is encrypted).

Anyway, @SBrandeis, I would love to learn how to create a machine user specifically for this (maybe for a future use case)...

**Pull request merged**
