### PR TITLE
Simpler tagger

### PR DESCRIPTION
**Pull request by theo-m**
I have:
- [x] removed a bunch of modules whose purpose I couldn't really justify for what I want to use this for
- [x] added some query parameters to be able to point users to a given existing tagset
- [x] added some logic to highlight existing invalid tags in a loaded tagset
- [x] validated the language tags against the `langcodes` python package
- [x] added a script to build up-to-date tagsets
- [x] added a docker script to run this smoothly and try to deploy it in a `subdomain.huggingface.co` soon
- [ ] validated the tasks tagset

Here's a demo, you should be able to use it at [this address](http://35.205.12.130:8501/?preload_dataset=arabic_billion_words) but no guarantees.

Screenshot 2021-03-22 at 11 43 52

### CODE REVIEW

**Comment by yjernite** [comment]
LGTM! If you're using Streamlit for teams, you'll just need to change the redirection address here:
https://github.com/huggingface/conf/blob/028171b0c628f129fa3f1bfb4d1820060afd12d7/moonrise/nginx-moonrise.conf#L226 

(Lmk so I can retire the GCP instance currently running the app)

**Comment by yjernite** [comment]
Couple of quick comments on the currently deployed app:
- Is loading from the current README.md yaml WIP?
- choosing `other` opens an input widget in the wrong place currently (and fails the validation)
- the number of examples for the config used to be inferred from the `dataset_info.json` file, is there a reason to switch it back to manual input? Could we maybe auto-populate this field at least?

**Comment by theo-m** [comment]
> * Is loading from the current README.md yaml WIP?

I don't understand?

> * choosing `other` opens an input widget in the wrong place currently (and fails the validation)

for what selector does this happen?

> * the number of examples for the config used to be inferred from the `dataset_info.json` file, is there a reason to switch it back to manual input? Could we maybe auto-populate this field at least?

no reason, an oversight, will revert, thanks!

**Comment by theo-m** [comment]
> > * choosing `other` opens an input widget in the wrong place currently (and fails the validation)

found out, fixed!

**Pull request merged**
