### PR TITLE
Update tagging_app.py

### PR DESCRIPTION
**Pull request by gchhablani**
Add more size categories in the tagging app.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Cool ! <s>Should we change `1T` to `1B` ?</s>

EDIT: actually it looks like the 1B is missing, and then we can have 1T for trillion

**Comment by gchhablani** [comment]
@lhoestq 🙈 I missed it.

**Review by lhoestq — APPROVED** [review]
Thanks :)

**Comment by lhoestq** [comment]
cc @yjernite can you take a look at these changes ?
I don't have permissions on this repo

**Comment by yjernite** [comment]
Looks good to me, although I'm not sure how many datasets we have that fall in any of these categories (the size here is the total number of rows in the table in a single config)

@gchhablani did you have specific datasets in mind?

**Comment by gchhablani** [comment]
Hi @yjernite,

In the existing datasets, there are some above a billion, some above 10 million, I just thought it would be better for such datasets.

You can check the PR I made on datasets, a lot of the datasets(configs) are between 1M and 10M and some above 10M, where it was previous labelled as "n>1M".

I don't have anything specific in mind for 1T, but I think we can have it there, just in case something comes along.

Up to you and @lhoestq to decide :) I'll change everything back to "n>1M" if you'd like on the PR.

**Pull request merged**
